DROP DATABASE IF EXISTS example;
CREATE DATABASE IF NOT EXISTS example;

USE example

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT UNSIGNED NOT NULL PRIMARY KEY,
  name VARCHAR(255) COMMENT 'Имя пользователя'
) COMMENT = 'Пользователи';

